<%@ Page Title="Terms" Language="C#" MasterPageFile="~/Site.master" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <div class="mainDivPadding">
    <h2>Terms And Conditions</h2><br />
    <p>By using the GlutenFreeCouponKing.com website (herein after referred to as “GFCK”), you have agreed to these terms and conditions of use.  GFCK  may change the terms and conditions at any time and without actual notice to you.  All such changes will appear on GFCK.  When you use this site you agree to accept the current terms and conditions as posted, whether or not you have reviewed them.  Please do not use this site if you choose not to accept these terms and conditions.</p><br />
    <p>You acknowledge and agree that any content you view is at your own discretion and risk, including any reliance on the accuracy, completeness or merit of such content. All product information on this site, including but not limited to product ingredients and potential cross contamination, is the representation of the manufacturers of said products. GFCK is not responsible for the accuracy or completeness of  such information.  Product ingredients and information may change from time to time at the discretion of each manufacturer. As such, you must read the label of each product prior to purchasing. Be sure to check with the  manufacturer if you have any questions or concerns. All information provided by GFCK  is presented as of the date of posting.  We do not take responsibility for updating this information and are under no obligation to do so after it has been posted to this site.  You acknowledge that you may not rely on any information, data, text, sound, photographs, graphics, video, messages or other content created or submitted by GFCK.  You agree not to use any information provided as medical or health advice. Consult your personal physician if you have any medical or health concerns.</p><br />
    <p>GFCK  makes no warranties or claims of any kind about the products and services referenced in this site and in corresponding email updates.  Product and service performance is the sole responsibility of the manufacturers and companies providing these products and services.</p><br />
    <p>All content of GFCK, including text, images and graphics are protected by federal copyright law.  The content on this website is available solely for your personal and non-commercial use, subject to the terms and conditions set forth in this agreement.  You may not reproduce, modify or distribute, for commercial purposes, any or all of the content provided on this website without the expressed written permission of GFCK. GFCK is the sole owner of any information presented or collected on this website.</p><br />
    <p>From the GFCK website, you may be able to link to third parties’ websites.  GFCK  does not examine, review or control these linked sites in any way.  The content, availability, advertising, products or other materials, including additional links contained on any such linked sites, are not the responsibility of GFCK.  When you link from GFCK  to a third party website, you do so at your own discretion and risk. </p><br />
    <p>In no event shall GFCK be liable for any special, indirect, or consequential damages of any kind, including, without limitation, lost profits or damages that result from using any information provided on this website or any third party websites which may be linked to or from GFCK. </p><br />
    <p>By using GFCK  you represent that you are 18 years of age or older.  Do not use this site, and do not register for GFCK emails if you are not at least 18 years of age.  By using GFCK, you represent that you have the authority and capacity to agree to and abide by these terms and conditions. GFCK is a United States based website, intended for U.S. users. Product ingredients may vary based on the country of manufacture. If you reside outside of the United States, use of this site is at your own risk and you assume full responsibility for compliance with any applicable local laws. All promotions offered are limited to United States residents. </p><br />
    <p>Distribution of any coupon available on GFCK in PDF or other portable document format is not permitted. Such coupons are void if copied, altered, reproduced, sold, transferred or exchanged. Any misuse constitutes fraud and is prosecutable under federal wire and other statutes. Civil and criminal penalties exceeding $2,000,000 and/or imprisonment may apply.</p><br /><br />
    </div>
</asp:Content>
